Repository pencil2d/pencil, pull requests merged in 2019-08, with the labels that each got.

#1249 Autosave & Grid preference settings adjustment
  app/ui/filespage.ui
  app/ui/generalpage.ui
  core_lib/src/managers/preferencemanager.cpp
Labels: enhancement, preferences

#1252 Move onion skin mode selector to the preferences window
  app/src/mainwindow2.cpp
  app/src/preferencesdialog.cpp
  app/src/preferencesdialog.h
  app/ui/toolspage.ui
  core_lib/src/interface/timeline.cpp
  core_lib/src/interface/timeline.h
Labels: enhancement, onion skin, timeline

#1253 Fix all spin boxes maintaining focus after returning
  app/src/colorinspector.cpp
  app/src/tooloptionwidget.cpp
  core_lib/src/interface/timecontrols.cpp
  core_lib/src/util/util.cpp
  core_lib/src/util/util.h
Labels: bug, ux

#1251 Fix onion skin rendering and behavior
  core_lib/src/canvaspainter.cpp
  core_lib/src/interface/timelinecells.cpp
  core_lib/src/structure/layer.cpp
Labels: bug, onion skin
