Repository pencil2d/pencil, pull requests merged in 2019-11, with the labels that each got.

#1285 #1177 Import drawings on wanted position
  app/app.pro
  app/src/importexportdialog.cpp
  app/src/importexportdialog.h
  app/src/importimageseqdialog.cpp
  app/src/importimageseqdialog.h
  app/src/importpositiondialog.cpp
  app/src/importpositiondialog.h
  app/src/mainwindow2.cpp
  app/ui/importexportdialog.ui
  app/ui/importpositiondialog.ui
  core_lib/src/interface/editor.cpp
  core_lib/src/managers/viewmanager.h
  core_lib/src/util/pencildef.h
Labels: :small_blue_diamond:, import-export

#1276 #177 Save and Load shortcut list
  app/src/shortcutspage.cpp
  app/src/shortcutspage.h
  app/ui/shortcutspage.ui
Labels: :small_blue_diamond:, request: core

#1269 Miscellaneous bugfixes
  app/src/actioncommands.cpp
  app/src/mainwindow2.cpp
  app/ui/displayoption.ui
  app/ui/exportimageoptions.ui
  app/ui/exportmovieoptions.ui
  app/ui/toolboxwidget.ui
  core_lib/src/canvaspainter.cpp
  core_lib/src/graphics/vector/beziercurve.cpp
  core_lib/src/graphics/vector/beziercurve.h
  core_lib/src/interface/editor.cpp
  core_lib/src/interface/scribblearea.cpp
  core_lib/src/interface/scribblearea.h
  core_lib/src/managers/layermanager.cpp
  core_lib/src/managers/soundmanager.cpp
  core_lib/src/structure/layersound.cpp
  core_lib/src/tool/brushtool.cpp
  core_lib/src/tool/erasertool.cpp
  core_lib/src/tool/erasertool.h
  core_lib/src/tool/polylinetool.cpp
  core_lib/src/util/pointerevent.cpp
  core_lib/src/util/pointerevent.h
Labels: :small_blue_diamond:, bug
