Repository pencil2d/pencil, pull requests merged in 2020-12, with the labels that each got.

#1492 Use thinner cross cursor
  core_lib/data/core_lib.qrc
  core_lib/data/icons/cross.png
  core_lib/src/tool/basetool.cpp
  core_lib/src/tool/brushtool.cpp
  core_lib/src/tool/buckettool.cpp
  core_lib/src/tool/erasertool.cpp
  core_lib/src/tool/eyedroppertool.cpp
  core_lib/src/tool/penciltool.cpp
  core_lib/src/tool/pentool.cpp
  core_lib/src/tool/polylinetool.cpp
Labels: Enhancement, UI

#1547 Fix extra movement when moving vector objects
  core_lib/src/interface/scribblearea.cpp
Labels: Bug, Transform, Vector

#1545 Restructure startup around application class
  app/app.pro
  app/src/commandlineexporter.cpp
  app/src/commandlineexporter.h
  app/src/commandlineparser.cpp
  app/src/commandlineparser.h
  app/src/main.cpp
  app/src/mainwindow2.cpp
  app/src/mainwindow2.h
  app/src/pencil2d.cpp
  app/src/pencil2d.h
  app/src/pencilapplication.cpp
  app/src/pencilapplication.h
  core_lib/src/interface/editor.cpp
  core_lib/src/interface/editor.h
  core_lib/src/interface/scribblearea.cpp
  core_lib/src/interface/scribblearea.h
  core_lib/src/structure/layercamera.cpp
  core_lib/src/structure/layercamera.h
  core_lib/src/structure/object.cpp
  core_lib/src/structure/object.h
  core_lib/src/util/fileformat.cpp
  core_lib/src/util/fileformat.h
Labels: Refactoring

#1497 Fix canvas showing wrong content after moving frames
  app/src/actioncommands.cpp
  app/src/mainwindow2.cpp
  core_lib/src/interface/editor.h
  core_lib/src/interface/scribblearea.cpp
  core_lib/src/interface/scribblearea.h
  core_lib/src/interface/timelinecells.cpp
  core_lib/src/structure/layer.cpp
  core_lib/src/structure/layer.h
  tests/src/test_layer.cpp
Labels: :small_blue_diamond:, Bug
