Repository pencil2d/pencil, pull requests merged in 2020-09, with the labels that each got.

#1451 Miniz improvements
  core_lib/src/qminiz.cpp
  core_lib/src/util/util.h
Labels: Enhancement, File Load, File Save, Refactoring

#1443 More bugfixes
  app/src/mainwindow2.cpp
  core_lib/src/canvaspainter.cpp
  core_lib/src/interface/scribblearea.cpp
  core_lib/src/interface/scribblearea.h
  tests/src/test_filemanager.cpp
Labels: Bug

#1430 1427 Pclx import crash
  app/src/importlayersdialog.cpp
  app/src/importlayersdialog.h
  app/src/mainwindow2.cpp
  app/ui/importlayersdialog.ui
  app/ui/mainwindow2.ui
  core_lib/src/structure/layer.cpp
  core_lib/src/structure/layer.h
  core_lib/src/structure/object.cpp
  core_lib/src/structure/object.h
Labels: :small_blue_diamond:, Bug, Crash, File Import

#1400 Draw the timeline using palette colours (AKA dark theme support for the timeline)
  core_lib/src/interface/timelinecells.cpp
  core_lib/src/structure/layer.cpp
Labels: Timeline, UI, User Customization

#1434 #1433 - Fix polyline painting issue for vector
  core_lib/src/canvaspainter.cpp
Labels: Polyline Tool, Vector
