Repository pencil2d/pencil, pull requests merged in 2020-05, with the labels that each got.

#1333 Sound scrubbing, using shortcuts or mouse
  app/data/app.qrc
  app/data/icons/controls/soundscrub-disabled.png
  app/data/icons/controls/soundscrub.png
  app/src/mainwindow2.cpp
  app/src/mainwindow2.h
  app/src/preferencesdialog.cpp
  app/src/preferencesdialog.h
  app/ui/timelinepage.ui
  core_lib/src/interface/editor.cpp
  core_lib/src/interface/timecontrols.cpp
  core_lib/src/interface/timecontrols.h
  core_lib/src/interface/timeline.cpp
  core_lib/src/interface/timelinecells.cpp
  core_lib/src/interface/timelinecells.h
  core_lib/src/managers/playbackmanager.cpp
  core_lib/src/managers/playbackmanager.h
  core_lib/src/managers/preferencemanager.cpp
  core_lib/src/managers/preferencemanager.h
  core_lib/src/soundplayer.cpp
  core_lib/src/soundplayer.h
  core_lib/src/structure/soundclip.cpp
  core_lib/src/structure/soundclip.h
  core_lib/src/util/pencildef.h
Labels: help wanted, sound

#1341 Fix #1033 Broken sound playback in AppImages
  .travis.yml
  app/src/main.cpp
  util/after-build.sh
Labels: os:linux, packaging, sound

#1258 Movie import
  app/src/actioncommands.cpp
  app/src/actioncommands.h
  app/src/filedialogex.cpp
  app/src/filedialogex.h
  app/src/mainwindow2.cpp
  app/src/mainwindow2.h
  app/src/preferencesdialog.cpp
  app/ui/mainwindow2.ui
  core_lib/core_lib.pro
  core_lib/src/external/linux/linux.cpp
  core_lib/src/external/macosx/macosx.cpp
  core_lib/src/external/win32/win32.cpp
  core_lib/src/interface/editor.cpp
  core_lib/src/interface/editor.h
  core_lib/src/movieexporter.cpp
  core_lib/src/movieexporter.h
  core_lib/src/movieimporter.cpp
  core_lib/src/movieimporter.h
  core_lib/src/util/fileformat.h
  core_lib/src/util/filetype.h
  core_lib/src/util/pencildef.h
  core_lib/src/util/pencilerror.cpp
  core_lib/src/util/pencilerror.h
  core_lib/src/util/util.cpp
  core_lib/src/util/util.h
Labels: :large_blue_diamond:, import-export

#1348 Appimage sound followup
  .travis.yml
  app/src/main.cpp
  core_lib/src/external/linux/linux.cpp
  core_lib/src/external/macosx/macosx.cpp
  core_lib/src/external/platformhandler.h
  core_lib/src/external/win32/win32.cpp
  util/after-build.sh
Labels: bug, os:linux, refactoring, sound

#1347 Add install support for other Unixes
  app/app.pro
Labels: os:mac, os:other, packaging

#1351 Add an action to open Pencil2D's temporary directory
  app/src/actioncommands.cpp
  app/src/actioncommands.h
  app/src/mainwindow2.cpp
  app/ui/mainwindow2.ui
Labels: request: enhancement, ux

#1035 add linux appdata
  app/app.pro
  app/data/org.pencil2d.Pencil2D.metainfo.xml
Labels: :small_blue_diamond:, os:linux, packaging
