Repository pencil2d/pencil, pull requests merged in 2020-04, with the labels that each got.

#1326 Fix playback audio sync issues
  core_lib/src/managers/playbackmanager.cpp
  core_lib/src/soundplayer.cpp
Labels: :small_blue_diamond:, bug, sound

#1324 Increase visibility of active layer keyframes
  core_lib/src/interface/timelinecells.cpp
  core_lib/src/interface/timelinecells.h
  core_lib/src/structure/layer.cpp
  core_lib/src/structure/layer.h
Labels: :small_blue_diamond:

#1317 Layout tweaks
  app/src/displayoptionwidget.cpp
  app/src/displayoptionwidget.h
  app/src/toolbox.cpp
  app/src/toolbox.h
  app/ui/displayoption.ui
  app/ui/onionskin.ui
  core_lib/src/interface/basedockwidget.cpp
  core_lib/src/interface/basedockwidget.h
  core_lib/src/interface/flowlayout.cpp
Labels: :small_blue_diamond:, UI

#1339 Fix OnionSkinWidget Prev/Next Button Behavior
  app/src/onionskinwidget.cpp
Labels: UI, bug, onion skin, ux

#1318 Fix MinGW windows compiling issues
  app/app.pro
  core_lib/src/miniz.cpp
  tests/tests.pro
  util/after-build.ps1
Labels: compilation, os:win
