Repository pencil2d/pencil, pull requests merged in 2020-08, with the labels that each got.

#1404 Handle angle-based high resolution scrolling properly
  core_lib/src/interface/scribblearea.cpp
  core_lib/src/managers/viewmanager.cpp
  core_lib/src/managers/viewmanager.h
  core_lib/src/structure/camera.cpp
  core_lib/src/structure/camera.h
  core_lib/src/tool/handtool.cpp
  core_lib/src/tool/handtool.h
Labels: request: enhancement, ux

#1424 Fix temporary tools getting stuck if changing applications
  app/src/main.cpp
  app/src/mainwindow2.cpp
  app/src/mainwindow2.h
  app/src/pencilapplication.cpp
  app/src/pencilapplication.h
  core_lib/src/interface/scribblearea.cpp
Labels: :small_blue_diamond:, bug

#1422 Only creating keyframes that exists in *.pclx: The Sequel
  core_lib/src/structure/object.cpp
Labels: :small_blue_diamond:, bug, bug: file load

#1425 Open last project
  app/src/mainwindow2.cpp
  app/src/mainwindow2.h
  app/src/preferencesdialog.cpp
  app/src/preferencesdialog.h
  app/ui/filespage.ui
  app/ui/presetdialog.ui
  core_lib/src/managers/preferencemanager.cpp
  core_lib/src/managers/preferencemanager.h
  core_lib/src/util/pencildef.h
Labels: :small_blue_diamond:, Bug: File Load, Request: Enhancement, UI

#1431 1428 fix crash under peculiar circumstances
  app/src/mainwindow2.cpp
Labels: Bug, Crash

#1419 New layer naming #1414
  app/src/actioncommands.cpp
  core_lib/src/managers/layermanager.cpp
Labels: :small_blue_diamond:, Bug, Layer Management

#1369 Make onion skin widget scrollable
  app/ui/onionskin.ui
Labels: UI
