Repository pencil2d/pencil, pull requests merged in 2021-03, with the labels that each got.

#1581 Fix more cache issues.
  app/src/actioncommands.cpp
  core_lib/src/interface/editor.cpp
  core_lib/src/managers/viewmanager.cpp
Labels: Bug

#1558 Replace AppVeyor and Travis CI with GitHub Actions
  .github/actions/create-package/action.yml
  .github/actions/create-package/create-package.sh
  .github/actions/install-dependencies/action.yml
  .github/actions/install-dependencies/install-dependencies.sh
  .github/actions/setup-environment/action.yml
  .github/actions/setup-environment/setup-environment.sh
  .github/actions/upload-package/action.yml
  .github/actions/upload-package/nightly-build-upload.py
  .github/actions/upload-package/pr-build-upload.py
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .travis.yml
  app/app.pro
  appveyor.yml
  core_lib/core_lib.pro
  tests/tests.pro
  translations/translations.qrc
  util/.gitignore
  util/after-build.ps1
  util/checkchanges-win.ps1
  util/checkchanges.sh
  util/common.pri
  util/documentation-deploy.sh
Labels: Continous Integration

#1355 459 Layer / Keyframe opacity
  app/app.pro
  app/src/actioncommands.cpp
  app/src/layeropacitydialog.cpp
  app/src/layeropacitydialog.h
  app/src/mainwindow2.cpp
  app/src/mainwindow2.h
  app/ui/layeropacitydialog.ui
  app/ui/mainwindow2.ui
  core_lib/src/canvaspainter.cpp
  core_lib/src/graphics/bitmap/bitmapimage.cpp
  core_lib/src/graphics/bitmap/bitmapimage.h
  core_lib/src/graphics/vector/vectorimage.cpp
  core_lib/src/graphics/vector/vectorimage.h
  core_lib/src/structure/layer.cpp
  core_lib/src/structure/layer.h
  core_lib/src/structure/layerbitmap.cpp
  core_lib/src/structure/layerbitmap.h
  core_lib/src/structure/layervector.cpp
  core_lib/src/structure/object.cpp
Labels: Feature Request, Layer Management
