Repository pencil2d/pencil, pull requests merged in 2022-08, with the labels that each got.

#1719 Store nightly builds as artifacts
  .github/actions/create-package/action.yml
  .github/actions/create-package/create-package.sh
  .github/actions/install-dependencies/action.yml
  .github/actions/install-dependencies/install-dependencies.sh
  .github/actions/setup-environment/action.yml
  .github/actions/upload-package/action.yml
  .github/actions/upload-package/nightly-build-upload.py
  .github/actions/upload-package/pr-build-upload.py
  .github/workflows/ci.yml
Labels: Continous Integration

#1265 Update swatches after Replace command
  app/src/colorpalettewidget.cpp
  app/src/colorpalettewidget.h
  app/src/mainwindow2.cpp
  core_lib/src/graphics/vector/vectorimage.cpp
  core_lib/src/managers/colormanager.cpp
  core_lib/src/managers/colormanager.h
  core_lib/src/tool/eyedroppertool.cpp
  tests/src/test_colormanager.cpp
  tests/src/test_vectorimage.cpp
  tests/tests.pro
Labels: Bug, Color Palette, :small_blue_diamond:

#1718 Improved new-user experience
  README.md
Labels: Enhancement, Documentation
