Repository pencil2d/pencil, pull requests merged in 2022-06, with the labels that each got.

#1702 Check for multiple application instances
  app/src/main.cpp
  app/src/pencil2d.cpp
  app/src/pencil2d.h
Labels: Enhancement, UX, :small_blue_diamond:

#1468 Toolbars
  app/data/app.qrc
  app/data/icons/grid.png
  app/data/icons/zoom-in.png
  app/data/icons/zoom-out.png
  app/data/icons/zoom-reset.png
  app/src/mainwindow2.cpp
  app/src/mainwindow2.h
  app/ui/mainwindow2.ui
Labels: Feature Request, UX

#1682 Paste from previous frame
  app/src/mainwindow2.cpp
  app/src/shortcutspage.cpp
  app/ui/mainwindow2.ui
  core_lib/data/resources/kb.ini
  core_lib/src/interface/editor.cpp
  core_lib/src/interface/editor.h
  core_lib/src/util/pencildef.h
Labels: Feature Request, QoL
