Repository pencil2d/pencil, pull requests merged in 2024-05, with the labels that each got.

#1835 Fix build server only deploys arm64 macOS binaries
  .github/actions/create-package/create-package.sh
  .github/workflows/ci.yml
Labels: macOS, Continous Integration

#1827 Update to WiX 5
  .github/actions/create-package/create-package.sh
  .github/actions/install-dependencies/install-dependencies.sh
  docs/installer-development.md
  util/installer/pencil2d.bundle.wxs
  util/installer/pencil2d.cpp
  util/installer/pencil2d.pro
  util/installer/pencil2d.thm
Labels: Packaging, Windows

#1832 Update AppStream summary and add brand colors
  app/data/org.pencil2d.Pencil2D.metainfo.xml
Labels: Enhancement, Packaging, Linux
